modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="cemm"
version="1.9.27"
displayName="CE's Minerals & More"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="CEntertain"
description='''
First Release Copy
'''

[[dependencies.cemm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




